### ISSUE TITLE
commands after ssh

### ISSUE THREAD

**Issue by aiex** [fitztrev/shuttle#119]
hi,
   nice work so far.
   here is what i want:
   {	
       "name": "ssh",
       "cmd": "sshpass -p 123456 ssh username@dev.example.com; cd usr/test"
  },

 it seems the cmd only runs the local commands, i have tried sh script, it appears the same.

**Comment by dpedu** [comment]
This is a bad idea because your ssh password will be left in the clear in your bash history.

Also, the command you specified won't do what you want. Your command will open an ssh session to  username@dev.example.com. Then, when the ssh connection exits, you will cd to usr/test on your *local* machine.

**Comment by thshdw** [comment]
@aiex You can run a bash script in the cmd. Using the latest release you can also have this command run in new window
```
{
"name": "My bash ",
"cmd": "sh ~/Documents/path/to/my/script.command",
"inTerminal": "new"
},
```
@dpedu is correct you should not place ssh passwords in a script.
