### ISSUE TITLE
Shuttle crashed after error reporting

### ISSUE THREAD

**Issue by andreasisaak** [fitztrev/shuttle#152]
After the message of #151 (not allowed value) the shuttle app crashed. I need to restart the app after every try in the config file ;)

**Comment by thshdw** [comment]
Are you getting any error messages?

**Comment by andreasisaak** [comment]
Nope. Only the message that the value xxx in "inTerminal" is not allowed.

**Comment by thshdw** [comment]
From the readme.md...

```"inTerminal": "VALUE",```

This sets how command will open in the terminal window. (Command setting)

Possible values are ```new```, ```tab```, or ```current```

new opens the command in a new terminal window.

tab opens the command in the active terminal window in a new tab.

current opens the command in the active terminal's window.

When using using current I recommend that you wrap the command in some user input like this:

```echo "are you sure y/n"; read sure; if [ "$sure" == "y" ]; then echo "running command" && ps aux | grep [s]sh; else echo "exiting..."; fi```

Do this as a precaution as it could be possible to run a command on the wrong host.

**Comment by andreasisaak** [comment]
My config are "inTerminal": "new"
But why i need to wrap my long code from #151 in this crazy sort of bash code?

**Comment by thshdw** [comment]
@andreasisaak I only suggest to wrap your command in the bash script if your ```inTerminal``` setting was set to ```current``` This is only suggested as a precaution. Because the command would run in the current terminal window you have the potential to run a command or script on the wrong terminal window / server.  I have a feeling that #151 is related to #153. Once I have #153 fixed lets try your sshfuse command again. I hope to have 1.2.6 out by next weekend. :smile: 
Thanks!

**Comment by andreasisaak** [comment]
All right. Now I understand it :)
