### ISSUE TITLE
changing editor to vim has no effect in osx

### ISSUE THREAD

**Issue by ashee** [fitztrev/shuttle#167]
Settings->Edit always brings up SublimeText even though I have changed editor settings to vim in my ~/.shuttle.json

```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "vim",
  "iTerm_version": "2.1.4",
  "launch_at_login": true,
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "terminal": "iTerm",
 ...
```

**Comment by thshdw** [comment]
Hello @ashee 

I think the issue here is the "iTerm_version" setting... this setting can only be ```stable``` or ```nightly```

**Comment by thshdw** [comment]
@ashee Did changing the value of ```"iTerm_version": "VALUE",``` work for you?

**Comment by ashee** [comment]
Unfortunately, it seems to have no effect. I restarted shuttle a number of times - no joy.

```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "vim",
  "iTerm_version": "nightly",
  "launch_at_login": true,
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "terminal": "iTerm",
```

**Comment by ashee** [comment]
I should also mention that I have tried "iTerms_version": "stable" as well.

**Comment by thshdw** [comment]
Are you using the latest release,1.2.6

**Comment by ashee** [comment]
Ok - that was the issue. I was on 1.2.2 - upgraded to 1.2.6 which works.
However, the iTerm session that it opens is not the Default profile with my
fonts and color. Any tips to launch into my preferred iTerm profile?

**Comment by thshdw** [comment]
Thanks for the update! 

Regarding your profile... in iTerm click on Apple Menu > Preferences > Profiles. 

* Make sure that you have a Profile called Default. If you dont have this Press the + button make make new profile called Default.

* Next in your shuttle.json add below your ```"editor": "vim",``` line ```"default_theme": "ThemeName",``` Where ThemeName is the actual name of your theme.

Here is what the readme.md says on this 

#### ```"default_theme": "Homebrew",```
_This sets the Terminal theme for all windows. (Global Setting)_ 

Possible values are the Profile names in your terminal preferences. iTerm ships with one Profile named "Default". OS X Terminal ships with several. To see the names see the preferences area of the terminal you are using.

In iTerm the profile names are case sensitive.

**Please ensure the theme names you set are valid. If shuttle passes theme "Dagobah" and it does not exist in iTerm or OS X Terminal then your command won't run. This is because the applescripts are not making any checks to see if the theme you passed actually exists within the terminal application.** 

This setting can be overwritten by the command level ```"theme"``` settings

**Comment by thshdw** [comment]
@ashee Did the above help with your preferred iTerm profile issue?

**Comment by thshdw** [comment]
I think that this is resolved... if not please reopen 😄
