### ISSUE TITLE
sshfs commands

### ISSUE THREAD

**Issue by tarikaltuncu** [fitztrev/shuttle#189]
Interestingly, when I try to send any sshfs command through shuttle app it does not work. Moreover, all command buttons in the app's menu becomes disabled

        {
          "cmd": "sshfs -i public_key uname@address:/ /path/to/local/  -oauto_cache,reconnect,defer_permissions,noappledouble,negative_vncache,volname=remote_volume -o cache=no",
          "name": "Mount Remote Server File System"
        }

**Comment by thshdw** [comment]
Hello @tarikaltuncu has this ever worked?

**Comment by thshdw** [comment]
Also, I've never used sshfs. In OS X are you expecting finder to open the path or are just expecting the remote path to mounted as sshfs?

**Comment by tarikaltuncu** [comment]
Hello @thshdw 

I do not expect finder to open the path but just pop up an iTerm2, mount as sshfs then terminate the iTerm2.

I found a workaround. I put the command into an executable .sh file and call that file using the shuttle.app. This works now :)

Thanks

**Comment by tarikaltuncu** [comment]
A working example is as this:

{
          "cmd": "path/to/shfile && ./mountsshfs.sh && exit 0",
          "name": "File System"
}

**Comment by thshdw** [comment]
Thanks for the update. 

I think that the issue is with the way the shuttle parses commands. shuttle is checking the command to see if it contains a URL like ```http://www.google.com``` or ```cifs://myServer/c$``` and tries to open that in the default app. My guess is that shuttle did not like this in your command ```uname@address:/ ```

If your goal is to just run the command so it mounts the file system for you... then your workaround is the suggested method.
