### ISSUE TITLE
Can Shuttle just write command in console instead of executing it?

### ISSUE THREAD

**Issue by bocharsky-bw** [fitztrev/shuttle#200]
Can Shuttle write command in my terminal but do not execute it? Is it possible? I'd to slightly change some my commands before executing them. It'll be very useful if I have such option in config.

**Comment by bocharsky-bw** [comment]
ping @fitztrev

**Comment by thshdw** [comment]
@bocharsky-bw  I don't think this is possible. Applescript is the thing that is sending the commands to terminal. I don't believe there is a way to have applescript send a command to terminal but not execute it.  I'll research this for you.

You could wrap your command in some input, y/n choices... if choice is no then you could do something with it.

**Comment by bocharsky-bw** [comment]
Hey @thshdw , thank you! I'm wondering what you will find.

Btw, I've found a workaround for me: I add `#` in the beginning of commands, then I can easily modify this commented out command by hand and execute it again.

**Comment by thshdw** [comment]
@bocharsky-bw You're Welcome. Until then you can use
```history -s myCommand```

You can add this to your command like you normally would like this...
```"cmd": "history -s ps aux | grep [a]pple",```

The above would add ```ps aux | grep [a]pple``` to your bash history and you could press the up arrow to insert the last command for bash editing. 

or you could wrap this in some user input giving you the choice to run the command directly or add it to history like this....

```"cmd": "echo '—->WARNING<-- Running Command! Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command... && ps aux | grep [a]pple; else echo saving unused command to history... && history -s ps aux | grep [a]pple; fi",```

The above gives you the option to run the command as is by pressing ```y``` or adding it to the history by pressing ```n``` 

If it turns out that applescript can't do what you want this seems to be an adequate workaround

**Comment by thshdw** [comment]
@bocharsky-bw There does not seem to be a way to do what you request with applescript. 

You can see the terminal applescript dictionary on your mac. To do this run ```Script Editor``` press file > Open Dictionary... select Terminal from the list. In the dictionary the only command for getting text into the terminal window is:
 ```do script``` *v : Runs a UNIX shell script or command*

try the ```history -s myCommand``` (up arrow) workaround I think you will be happy with this.

**Comment by thshdw** [comment]
@bocharsky-bw Using a combination of ```history -s``` and ```osascript -e``` on my development system I have created a shuttle command that adds something the the bash history and then presses ```control``` + ```p``` which displays the last line from bash history; ready for editing. 

It's not working on the current release due to #194 . :slightly_frowning_face: 

Once this bug is fixed, shuttle can do what you request using a specially crafted command. I think I'll add this to the default shuttle.json as its pretty useful :smile:

**Comment by thshdw** [comment]
Here is the specially crafted command.

```"cmd": "echo '—->WARNING! Running commands<-- Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command && ps aux | grep [a]pple; else echo save to history and show... && history -s 'ps aux | grep [a]pple' && osascript -e 'tell application \"System Events\" to keystroke \"p\" using {control down}'; fi",```

**Comment by bocharsky-bw** [comment]
Hm, by executing the `history -s ps aux | grep [a]pple` command I'm getting the next error:
> fc: too many arguments

I wonder, do I need to install some package to make it works?

**Comment by thshdw** [comment]
do 
```history -s 'ps aux | grep [a]pple'```

**Comment by bocharsky-bw** [comment]
Hm, I have the same output too :(
> fc: too many arguments

**Comment by thshdw** [comment]
@bocharsky-bw I'm in gitter if you want to chat.

**Comment by thshdw** [comment]
I can run the ```history -s 'ps aux | grep [a]pple'``` in terminal and it works just fine

**Comment by thshdw** [comment]
This is in the current release in the shuttle.json file. For reference I'm posting it here too. 

```
"cmd": "echo '—->WARNING! Running commands<-- Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command && ps aux | grep [a]pple; else echo save to history and show... && history -s 'ps aux | grep [a]pple' && osascript -e 'tell application \"System Events\" to keystroke \"p\" using {control down}'; fi",
```

**Comment by bocharsky-bw** [comment]
Thanks!

**Comment by thshdw** [comment]
You're Welcome!
