### ISSUE TITLE
Is this possible with Shuttle App?

### ISSUE THREAD

**Issue by JayHoltslander** [fitztrev/shuttle#218]
@fitztrev Is this possible? In a single click I'd like to be able to open two Terminal windows for the same ssh connection and run a different command in each window.

**Comment by Tensho** [comment]
I guess regarding your question issue title should be something like "Two terminal windows by one command" ^_~
I think no, as far as you configure Shuttle to run *one* command in *one* new window, new tab or current tab. I suppose the only way right now for you to choose `"inTerminal": "current"` and run command which will open 2 separate tabs with ssh commands by itself.

**Comment by thshdw** [comment]
@JayHoltslander This is not possible. What I would do is build a menu item for your ssh server. Then you would make 2 menu commands using the ```"inTerminal": "current"``` option. 

With the SSH server terminal window in focus you would run your commands in the current window. 

The ```"inTerminal": "current"``` feature basically lets you repeat frequently used commands in the active terminal. If you are consistently doing something like ```ps aux | grep name```; instead of typing it, you simply place it in your shuttle menu and reuse it anywhere. Hope this helps 😄
